### ISSUE TITLE
Jupyter Notebook Support - Report integration with LabKey

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#3408]
#### Rationale
There has been some back end support for running a ipynb report in a docker image and being able to retrieve generated artifacts for display and rendering on the server. This story is to wire up support for configuring a docker report engine and creating (importing) reports into the standard report editor and being able to run / edit reports through the standard pathways that exist to execute reports.

#### Branch information
- Platform, docker, docker-rstudio - https://github.com/LabKey/platform/tree/fb_ipynb

#### Tasks
- [x] Engine configuration - 14
  - [x] refactor views and scripting interface - 5
  - [x] template for docker reports - 3
  - [x] docker report specific form fields - 2
  - [x] roundtrip to DB - 2
  - [x] delete stale docker image configs - 2
- [x] Connect report type to editor - 10+
  - [x] configure code mirror language extension - 2
  - [x] report specific editor options (import/export btns) - 5
  - [x] add report type to grids & manage views etc - 3
  - [x] help page (hidden for now)  _deferring until helper code is implemented_
- [x] Report execution
  - [x] associate engine configuration with saved reports
  - [x] push configuration into the docker service

**Comment by labkey-klum** [comment]
@labkey-robert, @mbellew I believe we wanted to simplify the amount of engine configuration options for the docker report as opposed to the R docker engine. Here's an example of the options available (at this moment) for comparison

![image](https://user-images.githubusercontent.com/5741543/172195102-3d06c68b-9ebd-46c8-9bbd-bc09c113f7c1.png)

![image](https://user-images.githubusercontent.com/5741543/172195224-fce7e472-e30b-4770-8fd7-ddc7a4dcbfc7.png)

**Comment by labkey-klum** [comment]
@labkey-robert do you prefer Jupyter Report or Notebook? Also, I just used this font awesome icon for the report. Let me know if we need Andrew to specify a different one.

![image](https://user-images.githubusercontent.com/5741543/172198968-1d66b61b-bfcc-4eb4-8b21-99e68d243718.png)

**Comment by labkey-robert** [comment]
@labkey-klum I think we want "Jupyter Report". "Jupyter Notebook" was renamed to "Jupyter Lab". I doubt there will be much confusion if we call it Jupyter Notebook but lets roll with "Jupyter Report" unless you feel otherwise.

**Comment by labkey-klum** [comment]
@labkey-hannah @labkey-robert 
After the feedback from the meeting yesterday, I updated the Jupyter report to pop up this dialog (for new reports only) so that users don't just land on a blank source page.

![image](https://user-images.githubusercontent.com/5741543/172657567-e6156d0c-6bb2-49af-8d95-6ecb1cc93010.png)

**Comment by labkey-hannah** [comment]
This is a good idea.
A suggestion on wording -

Would you like to initialize this Jupyter Report (ipynb) from a file
(recommended), or start with a blank report? [Import from file] or [Start
with blank report]
