### ISSUE TITLE
Jupyter Reports - follow on tasks for UI (Archived in SC)

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#3436]
#### Rationale
Creating a story to track miscellaneous tasks that can be completed after the primary story is delivered.

#### Tasks
- [ ] Refactor `ExternalScriptEngineReport, ScriptEngineReport, ScriptProcessReport` - 5
- [x] Help page for report config object - 3
- [x] Default script for new reports - 2
