### ISSUE TITLE
Issue 45896: CTE in LK sql adding suggested columns twice

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#3679]
[Issue 45896: CTE in LK sql adding suggested columns twice](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=45896)

**Tasks**

- [x] Manual testing - 2 @labkey-jeckels 
- [x] code review - 1 @labkey-jeckels 
- [x] teamcity review and merge
