### ISSUE TITLE
Assay Design Renaming - planning

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#3704]
[Spec](https://docs.google.com/document/d/1Cy0p98tLqgqAhu6NEGKn5nulGVKk0RJw3SgDhmO9iww/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/3703)

**Tasks**
- [x] Start functional spec (User Value Statement, Background, User scenarios) - 1hr
- [x] Finish functional spec - 2 hr  @labkey-robert 
   - [x] follow-up with @labkey-hannah on questions
   - [x] complete Link-to-study section
- [x] Functional review -.5 hr @labkey-hannah 
- [x] Update spec with feedback - 1hr  @labkey-robert 
- [x] Implementation plan - 3hr @XingY 
- [x] Dev review - 1hr @cnathe 
- [x] Test review -1hr @labkey-danield
