### ISSUE TITLE
Assay Design Renaming - dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#3705]
[Spec](https://docs.google.com/document/d/1Cy0p98tLqgqAhu6NEGKn5nulGVKk0RJw3SgDhmO9iww/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/3703)

**Tasks**
- [x] Use DBSeq instead of name in LSID for TSVAssay protocol and domains - 3h
   - [x] Only query for new DB Seq for protocol
   - [x] Pass the same seq to .core and .output protocol
   - [x] Pass the same seq to 3 domains (batch, run and result) 
   - [x] no need to migrate existing lsids
- [x] Update assay export/import with new LSID- 5h
   - [x] BatchProtocolLSID should no longer reference name
   - [x] domainUrl for 3 domains should no longer reference name
   - [x] action LSID
   - [x] OntologyEntryURISupport 
   - [x] folder import with name collide
- [x] updating name for TSVAssay - 5h
   - [x] Find all 3 related exp.protocol and update name
   - [x] Update all 3 exp.protocolparameter.applicationname record
   - [x] Update exp.domaindescriptor.name batch, run and result
- [x] Enable GPAT name update on designer UI - 1h
- [x] Fix audit log for assay name update - 1h
   - [x] An audit entry will be added per domain (batch, run and result) for the renaming event
- [x] Update custom view reference for renamed assays - 2h
   - [x] Instead of queryName, assay renaming will change part of the schema name, so can’t use handleQueryNameChange directly
- [x] Fix audit log msg for sample type and dataclass renaming - 1h
- [x] Fix stale import aliases - 2h
- [x] Fix ELN reference for sample type, dataclass and assays - 3h
- [x] Fix Sample Finder reference - 2h
- [X] [Manual test plan](https://docs.google.com/document/d/1Cy0p98tLqgqAhu6NEGKn5nulGVKk0RJw3SgDhmO9iww/edit#heading=h.e6gj012203y) - 1hr
- [x] update selenium tests - 2h
- [x] Feature verification - .5hr @labkey-hannah 
- [x] Manual testing/Manual Testing adjustments - 3hr @cnathe 
- [x] Code review/Code review feedback - 2hr @cnathe 
- [x] Automated test plan - 1h
- [x] Teamcity review and merge - 1hr
- [x] Docs handoff - .5hr
