### ISSUE TITLE
Jupyter Microservice, Server Side - dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#3709]
[Spec](https://docs.google.com/document/d/1rtaKsgcDVF_TThP1rrvhhkbcC1xJi4G_g3lcq5RimXQ/edit?usp=sharing)

**Tasks**
- [x] wrap nbconvert service with nodejs - 2 @labkey-matthewb 📌
- [ ] update Dockerfile - 2 @labkey-matthewb 
- [ ] Update build/deploy documentation - 2 @labkey-matthewb 
- [ ] Update scripting admin UI - 3 @labkey-matthewb 
- [ ] startup property - 2 @labkey-matthewb 
- [ ] Update spec - 2 @labkey-matthewb 📌
