### ISSUE TITLE
Fix job indexing and notifications

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4031]
Fixing multiple issues with jobs:

* Comments aren't correctly indexed with jobs
* Jobs aren't reindexed when comments change
* Jobs aren't reindexed when job descriptions and other properties are changed
* Notifications aren't sent when comments are updated
* Comment edits aren't audited any more
* Automated tests aren't testing any of the above

[Issue 47088: LKSM: Task and task indexing are using obsolete comments](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=47088) includes some details.

**Tasks**
- [x] Add `DiscussionService.getDiscussions()` for cross-module, server-side retrieval of discussions - 2h @labkey-adam 
- [x] Index comments as part of job document - 1h @labkey-adam 
- [x] Add `DiscussionSrcTypeProvider.discussionChanged()` for cross-module notification of comment changes - 2h @labkey-adam 
- [x] Reindex jobs when description (and other properties) change - 1h @labkey-adam 
- [x] Re-add auditing of comment changes - 1h @labkey-adam 
- [x] Fix comment change email notifications - 2h @labkey-adam 
- [x] Code review - 1h @labkey-susanh @labkey-nicka 
- [x] TC review and Merge - 0.5h @labkey-adam
