### ISSUE TITLE
Performance fix: remove extra joins (core.containers)

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4153]
[Notes on ticket 47345](https://docs.google.com/document/d/1kgpRmT2oyN8c0vaM8OUFMqXo12oj8TcmWwIHPK6b5UM/edit?usp=sharing)

**Tasks** 
_adjust boilerplate tasks and hours below to fit the story._ 

- [x] remove extra joins (core.containers) @labkey-matthewb 
- [x] Code review(s) - 1hr 
- [x] Code review feedback - 1hr
- [ ] TC review and Merge - 1hr
