### ISSUE TITLE
Create "Created/CreatedBy/Modified/ModifiedBy" for Assay data rows - planning

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4261]
[Spec](https://docs.google.com/document/d/1v7MpLJPvgF8uU9Hdw78zFPy96ldsSaaqP-MJiCoENh4/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4259)

**Tasks** 
- [x] Start functional spec (User Value Statement, Success Metrics, Background, User scenarios) - 2hr @labkey-hannah 
- [x] Finish functional spec (Requirements, Open Questions, Detailed Functional Design, resolve comments) - 1 hr @labkey-robert 
- [x] Functional review - 1hr @labkey-susanh 
- [x] Update spec/resolve comments - .5 @labkey-robert @labkey-susanh  
- [x] Implementation plan - 3hr @cnathe 📍
- [x] Dev review - 1hr @XingY 
- [x] Test review  -1hr @labkey-tchad
