### ISSUE TITLE
Moving entities between projects - Audit service updates - dev

### ISSUE THREAD

**Issue by labkey-susanh** [LabKey/platform#4269]
[Epic](https://github.com/LabKey/sampleManagement/issues/1652)
[Spec](https://docs.google.com/document/d/1lGrJQJ4jtWDqQNnCoRsw2HkyOnvZJIpTgobX_XSNiWU/edit#heading=h.4l4ls9r259s6)

### Tasks
- [x] Investigate effects of moving samples without moving audit logs - 2h
- [x] SampleTimelineAuditProvider moveEvents - 0.5h
- [x] InventoryAuditProvider moveEvents - 0.5h
- [x] ExperimentAuditProvider moveEvents  - 0.5h
- [x] QueryUpdateAuditProvider moveEvents - 0.5h
- [x] AttachmentAuditProvider moveEvents - 1h
- [x] NotebookAuditProvider moveEvents - 1h
- [x] RecipeAuditProvider moveEvents - 1h
- [x] RegistryAuditProvider moveEvents - 1h
- [x] Update Spec - 0.5h
- [x] Code Review - 1h @cnathe 
- [x] Create automated test plan - 0.5h
- [x] TeamCity review and merge - 1h
