### ISSUE TITLE
CRI, Issue 47577: Add client API for renaming folders

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4323]
[Issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=47577)

**Tasks**
- [x] Server-side changes - 3 hr @RosalineP
    - [x] Implement 
    - [x] code review @cnathe 
    - [x] Merge 
- [x] Java - 3 hr @RosalineP 
    - [x] (Ramp up)
    - [x] Implement
    - [x] code review @labkey-ians 
    - [x] Manual Testing @labkey-ians 
    - [x] Implement updates @RosalineP 
    - [x] Merge @labkey-ians 
- [x] R - 2 hr @cnathe  https://github.com/LabKey/labkey-api-r/issues/91
    - [x] Implement
    - [x] Manual Testing @RosalineP 
    - [x] Merge
- [x] Python - 2 hr @RosalineP
    - [x] Implement
    - [x] code review
    - [x] Manual Testing
    - [x] Merge @labkey-alan 
- [x] JS - 2 hr @RosalineP 
    - [x] Implement
    - [x] Manual Testing - 2 @labkey-nicka 
    - [x] Merge
 - [x] Manual test plan 
 - [x] Create [Endpoint test against java api story on BZ](https://www.scrumwise.com/scrum/#/backlog-item/11103-lkcri-issue-47577-add-client-api-for-renaming-folders-automation-tests/id-1810-48372-26) - Pull out to another story, perhaps sweta can take this

**Comment by RosalineP** [comment]
**Manual Test Plan**
Calls will look different per API language. For basic browser console testing, the following scaffold can be used:
```
LABKEY.Ajax.request({
    method:'POST',
    url: LABKEY.ActionURL.buildURL('admin', 'RenameContainer.api'),
    jsonData: {
      ...
    },
    success: (r) => {console.log("success: ", r)},
    failure: (r) => {console.log("failure: ", r)}
})
```

General notes are:
- Name or title is required
- Title defaults to name unless specified
- AddAlias defaults true


Where the scenarios are as follows:
- [x] New name only: Verify name and title become 'name1'
{name: "name1"}
- [x] New title only: Verify only title changes to 'title2'
{title: "title2"}
- [x] New name and title: Verify both name and title update
{name: "name3", title: "title4"}
- [x] Required values missing: Verify error appears
{addAlias: true}
- [x] AddAlias explicitly true: Verify works, and name and title update
{name: "name4", addAlias: true}
- [x] AddAlias explicitly false: Verify works, and name and title update
{name: "name5", addAlias: false}
- [x] Empty name: Verify error appears
{name: " "}
- [x] Empty title: Verify error appears
{title: " "}
- [x] Empty name, populated title: Verify only title updates
{name: " ", title: "title6"}
- [x] Empty title, populated name: Verify name and title update
{name: "name7", title: " "}
- [x] Pre-existing name: Verify error appears
{name: (pre-existing container name)}

**Comment by Sigmonia** [comment]
After modifying the controller to the correct value

Where the scenarios are as follows:
- [x] New name only: Verify name and title become 'name1'
***Name is correct, title is blank/not set.***
- [x] New title only: Verify only title changes to 'title2'
- [x] New name and title: Verify both name and title update
- [x] Required values missing: Verify error appears
- [x] AddAlias explicitly true: Verify works, and name and title update
- [x] AddAlias explicitly false: Verify works, and name and title update
- [x] Empty name: Verify error appears
- [x] Empty title: Verify error appears
- [x] Empty name, populated title: Verify only title updates
- [x] Empty title, populated name: Verify name and title update
***Title is cleared***
- [x] Pre-existing name: Verify error appears

**Comment by RosalineP** [comment]
**R API**

- [x] New name only: Verify name and title become 'name1'
- [x] New title only: Verify only title changes to 'title2'
- [x] New name and title: Verify both name and title update
- [x] Required values missing: Verify error appears
- [x] AddAlias explicitly true: Verify works, and name and title update
- [x] AddAlias explicitly false: Verify works, and name and title update
- [x] Empty name: Verify error appears
- [x] Empty title: Verify error appears
- [x] Empty name, populated title: Verify only title updates
- [x] Empty title, populated name: Verify name and title update
- [x] Pre-existing name: Verify error appears
