### ISSUE TITLE
New line support for "Contains one of", "Doesn't Contains one of" etc - planning

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4407]
[Spec](https://docs.google.com/document/d/1148zLiMiyYkYbZd2mODGhH2kQK7XIdZGsK3lktnpWh0/edit?usp=sharing)
[Github project](https://github.com/LabKey/platform/issues/4406)

### Tasks 📍
- [x] Functional spec  - 2 hr @wendyinnis 
- [x] Design review - 1hr @labkey-andrewo 
- [x] Functional review - 1hr @labkey-susanh 
- [x] Update spec with functional review feedback -0.5hr @wendyinnis 
- [x] Re-Review - 0.5hr @labkey-susanh

**Comment by labkey-andrewo** [comment]
Design review done, I think the only thing to add is that we should spell out the delimiters we accept (semicolon or newline), because otherwise we're asking people to guess and commit them to memory.
