### ISSUE TITLE
New line support for "Contains one of", "Doesn't Contains one of" etc - implementation planning

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4445]
[Spec](https://docs.google.com/document/d/1148zLiMiyYkYbZd2mODGhH2kQK7XIdZGsK3lktnpWh0/edit?usp=sharing)
[Github project](https://github.com/LabKey/platform/issues/4406)

### Tasks 📍
- [x] Implementation plan - 1hr @cnathe 
- [x] Dev review - 1hr @XingY 
- [x] Update spec with feedback - 1hr
- [x] Test review  -1hr @labkey-danield 
- [x] Update spec with feedback - 1hr
