### ISSUE TITLE
New line support for "Contains one of", "Doesn't Contain one of" etc - dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4513]
[Spec](https://docs.google.com/document/d/1148zLiMiyYkYbZd2mODGhH2kQK7XIdZGsK3lktnpWh0/edit?usp=sharing)
[Github project](https://github.com/LabKey/platform/issues/4406)

### Tasks

- [x] App filter modal: toggle between textarea and text input based on filter type selection - 2h 
- [x] App filter modal: textarea placeholder text (and hover info?) - 1h 
- [x] App filter modal: parse textarea value to split on newline and trim - 2h 
- [x] App filter modal: reshow on filter modal open of existing filter - 2h
- [x] App filter label - 3 hr 
- [x] LKS grid filter modal: toggle between textarea and text input based on filter type selection - 2h 
    - [x] For filterDialog 
    - [x] For filterTab 
- [x] LKS grid filter modal: textarea placeholder text (and hover info?) - 2h
- [x] LKS grid filter modal: parse textarea value to split on newline and trim - 2h
- [x] LKS grid filter modal: reshow on filter modal open of existing filter - 2h
- [x] LKS customize view Selected Filters panel: implement same behavior - 3h
- [x] Update tests 
- [x] **REFACTOR** 
    - [x] Establish functionality assumptions @labkey-hannah 
    - [x] Finish updating tests 
    - [x] Ext tweaks @XingY 
    - [x] Revise PR 
    - [x] Update Spec - 0.5h 
    - [x] Code Review - 1h @XingY 
    - [x] Manual test updates - @XingY 
- [x] Create manual test plan - 1h 
- [x] Create automated test plan - 1h
- [x] Unit tests - 4 
- [x] Verify feature - 1hr @wendyinnis 
- [x] Manual testing - est range @labkey-chrisj 
- [x] Selenium test recommendations - 1
- [x] More tests
- [x] Get ui-components to run clean
- [x] Docs handoff - 0.5h
- [x] Test review and merge - 1h
