### ISSUE TITLE
Issue 48293:  Standard Assay with Plate Metadata & Transformation Script throws an error - Automated tests

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/platform#4616]
related [issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=48293)

### Tasks

- [x] sync with dev - 1 hr
- [x] Ramp-up- 1hr
- [x] Automated test plan - 1hr
- [x] Create No-Op transform script - 3hr 📍
- [x] Add transform script to `GpatPlateTemplateTest` - 1hr
- [x] Create API test case - 5hr
- https://github.com/LabKey/testAutomation/pull/1606 
- [x] Code review - 1hr
- [x] Code review feedback - 1hr
