### ISSUE TITLE
Assay Plate Metadata - dev

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#4621]
[spec](https://docs.google.com/document/d/1kS4hU7EvPnkXjs5dnNWhjhPbbSS3w0p8ydOJ0k7fgeg/edit#heading=h.hpvwefcmri7g)

**Rationale**
We would like to support adding metadata to plates, on a per well basis. While we have some support for this in the standard assay, it doesn't currently support all of the scenarios required for AB Discovery.

This phase of the development work will focus on creating a domain that can be attached to the `Assay.Well` table and be able to query and insert data associated with the vocabulary domain properties.

**Tasks**
- [x] Implemenation plan - 2
- [x] Ensure domain - 3 
- [x] CRUD operations for domain properties - 5
  - [x] Create properties
  - [x] Get properties
  - [x] Delete properites
- [x] Attach domain to `assay.well` table - 2
- [x] Support vocab domain in `WellTable` QUS - 3
- [x] Add sampleId to the `WellTable` - 2
- [x] Don't expose well columns : `value, dilution` - 2
- [x] Schema changes for plate / properties : 3
- [x] Clean up metadata on plate / container delete : 2
- [x] AddFields.api : 3
- [x] GetFields.api : 2
- [x] RemoveFields.api : 2
- [x] jest test fixes : 3
