### ISSUE TITLE
New line support for "Contains one of", "Doesn't Contains one of" etc - automated tests

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4630]
[Spec](https://docs.google.com/document/d/1148zLiMiyYkYbZd2mODGhH2kQK7XIdZGsK3lktnpWh0/edit?usp=sharing)
[Github project](https://github.com/LabKey/platform/issues/4406)

### Tasks 📍

- [x] Automated test plan - 1hr
- [x] Ramp up on existing test infra
- [x] Filter in QueryGrid in the apps 2
- [x] Filter in DataGrid filterpane in lks 2
- [x] Filter in column filter 2

**Comment by labkey-chrisj** [comment]
All of this stuff already had coverage. When Xing and Rosaline put in fixes to keep the tests going, they added cases for the new filters
