### ISSUE TITLE
AbDisc, Connect Plate Metadata to Assay data - dev

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#4636]
[spec](https://docs.google.com/document/d/1kS4hU7EvPnkXjs5dnNWhjhPbbSS3w0p8ydOJ0k7fgeg/edit#heading=h.hpvwefcmri7g)

**Rationale**
We would like to support adding metadata to plates, on a per well basis. While we have some support for this in the standard assay, it doesn't currently support all of the scenarios required for AB Discovery.

This phase of the development work will focus on creating a domain that can be attached to the `Assay.Well` table and be able to query and insert data associated with the vocabulary domain properties.

**Tasks**
- [x] Implemenation plan - 5
- [x] Conditionally add `WellLsid` field to the assay results domain - 3
- [x] `AssayPlateMetadataService` updates
  - [x] Implement an `ImportHelper` class to add additional bindings to join `assay.well` to results - 5
  - [x] Map incoming well location rows to existing `LSID` values on the `assay.well` table - 3
- [x] Add metric to track assays with plate metadata - 2 
- [x] Align with existing standard assay plate support - 3
- [x] Transform script support, merge in plate metadata - 5 📍 
- [x] Don't require metadata JSON file - 2
- [x] Plate endpoints
  - [x] Set Fields : 3
