### ISSUE TITLE
NIAID, Quanterix\ELISA assay integration - plan

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4654]
[Spec](https://docs.google.com/document/d/1dL-l5T1k_5m9kRz3ryDyD1qNeH7bpH10Vqjc84vpzJQ/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4651)
Harvest: NIAID - DCR - Custom Development - 8/1/23 - 7/31/24 - Quanterix\ELISA assay integration

### Tasks

- [x] Sync with NIAID, Prahba (8/8) - 1hr @cnathe @labkey-robert 
- [x] Functional spec - 3hr @cnathe 
- [x] Functional review - .5hr @labkey-robert 
- [x] Implementation plan and story breakdown - 3hr
- [x] Dev review @labkey-klum
