### ISSUE TITLE
AbDisc, Refactor Plate Cache, cache custom props

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#4673]
[spec](https://docs.google.com/document/d/1kS4hU7EvPnkXjs5dnNWhjhPbbSS3w0p8ydOJ0k7fgeg/edit#heading=h.hpvwefcmri7g)

**Rationale**
In order to reduce the number of queries we have to make for the Antibody Discovery MVP scenarios we want to try to push more information that can be cached. This includes well and potentially well metadata.

One thing that needs to be refactored is that currently the cache is scoped at the container level so when a plate is changed all plates will need to be re-queried. We want to change the cache to per-plate granularity, but one thing that complicates this is that we currently reference plates by:
- name
- lsid
- rowId
This makes it more complicated since a `BlockingCache` key is a single object.

**Tasks**
- [x] Cache at the per plate scope
  - [x] Implement cache key for name, lsid, rowid : 3
  - [x] Implement internal cache maps : 3
  - [x] serialize/deserialize cache key : 3
  - [x] Update endpoints : 2
  - [x] Implement cache removals : 3
  - [x] Use the plate cache where possible : 3 
- [x] Additional objects to cache
  - [x] Plate custom fields : 3
  - [x] Metadata domain : 2
  - [x] Ensure creation of metadata domain for Biologics folders (with experimental flag) : 3 
- [x] Move app plate experimental flag to assay module : 1
- [x] Update via Data Iterator not working for vocab properties : 3 
- [x] Plate metadata unit tests : 3
- [x] Remove well metadata endpoints : 2
