### ISSUE TITLE
NIAID, Quanterix\ELISA assay integration - file import dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4697]
[Spec](https://docs.google.com/document/d/1dL-l5T1k_5m9kRz3ryDyD1qNeH7bpH10Vqjc84vpzJQ/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4651)
Harvest: NIAID - DCR - Custom Development - 8/1/23 - 7/31/24 - Quanterix\ELISA assay integration

### Tasks

- [x] Create custom module or add new src dir to niaidElisa module - 1h
- [x] Add batch/run/results xml assay definition to module - 2-3h
- [x] React component for file drop to write to file system - 2-3h
- [x] Pipeline job task for processing Excel file "Summary Page" and importing as an assay run - 3h
- [x] Pipeline job task for processing "Curve Summary" sheets - 5h
- [x] File naming pattern, parsing, and validation of format - 1-2h
- [x] Attach file to the generated assay run (as a run input/output?) - 2-3h
- [x] File watcher configuration with new processing task - 1-2h
- [x] Code Review - 1hr @labkey-klum 
- [x] Update Spec - 1h
- [x] Create test plan - 1h
- [x] Manual Testing - 3h @labkey-robert 
- [x] Test review and merge
