### ISSUE TITLE
AbDisc: Hit Selection - server changes

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#4734]
[Github epic](https://github.com/LabKey/biologics/issues/2292)

### Tasks

- [x] Stop creating different Plate/WellGroup LSIDs based on template, instance, etc. - 3
- [x] Container filter support 
  - [x] For plate retrieval from cache via rowID - 3
  - [x] Via LSID - 2
  - [x] Consideration for cross folder data scenarios - 1 
- [x] Clean up legacy template terminology - 2
- [x] No longer allow resolving plates by name 📍 
  - [x] Refactor usages - 3
  - [x] Upgrade script for existing protocols - 3
  - [x] Delete legacy code, clean up plate cache - 3
