### ISSUE TITLE
AbDisc, Cross folder Plate Import

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#4782]
[Spec](https://docs.google.com/document/d/18Qr34Lrioar8HNFnbWh25LoOLQVP7ism4h8AKJJiGaA/edit)
[Github epic](https://github.com/LabKey/biologics/issues/2355)

#### Rationale
There is a current limitation on what plates are available for an assay to import and as of now, it is limited to the container that the assay definition exists in. For the phase 1 demos, the team would like to be able to define plates at the project and subfolder levels and make them available for any assay within the project. Additionally some valid scenarios were not working in the cross folder case:
- Assay and plate defined in the project, but importing data from a subfolder failed with a `resolve plate failed` error.
- Transform scripts were not able to merge in metadata when importing from a subfolder

The plan is to support these scenarios provided the experimental flags are enabled:
- Plate samples in Biologics
- Less restrictive product project lookups

### Tasks

- [x] Container filter for `PlateTemplate` table : 3
- [x] Resolve plates using `ContainerFilter` when importing assay data : 5
- [x] Merge well metadata to run results for transform scripts : 3 
- [x] In-use run counts : 2
- [x] Default assay run plate field target folder to : current : 1
