### ISSUE TITLE
Remove LabKey Employees from LKSM views - dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4812]
[Spec](https://docs.google.com/document/d/1aXDfb7_E7WnyOKOPXactMzheOir9T-hmgLxBRQl7xJA/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4799)

### Tasks 📍

- [x] Create role and permission [2]
- [x] Adjust permission checks [3]
- [x] Expand the power of TroubleShooters [3]
- [x] Expand the power of Impersonating Troubleshooters [2]
- [x] Revamp last Site Admin validation [3]
- [x] Miscellaneous clean up [3]
- [x] Fix failing tests [2]
- [x] Revamp restrictions on privileged roles [3]
- [x] Prohibit Application Admins from impersonating Site Admins & Developers [1]
- [x] Fix DisallowPrivilegedRolesContext, remove isAllowedGlobalRoles() [2]
- [x] Fix automated tests [3]
- [x] [Manual test plan](https://docs.google.com/document/d/1aXDfb7_E7WnyOKOPXactMzheOir9T-hmgLxBRQl7xJA/edit#heading=h.e6gj012203y) - .5hr @labkey-adam 
- [x] Code review - 1hr @josheckels 
- [x] Teamcity review and merge - 1hr
- [x] Docs handoff - .5hr 
- [x] Metrics handoff to @labkey-hannah   - .5hr @labkey-adam 
- [x] Feature verification to @labkey-hannah - .5hr @labkey-adam 
- [x] Manual testing - 2hr @labkey-tchad
