### ISSUE TITLE
Assay: Transform script UX update - functional planning

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4825]
[Spec](https://docs.google.com/document/d/1V6BeH_vu5pWyTedrtRK11qLV9Ks5-c5_wmkY7cUeGvk/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4823)

### Tasks
- [x] Ramp-up/sync w/ @bernarddlee @labkey-keegang  - 1hr @wendyinnis 
- [x] UX design @labkey-keegang 
- [x] Functional spec - 4hr @wendyinnis 
- [x] Functional review - .5hr @bernarddlee
