### ISSUE TITLE
Remove system users from LKSM views - selenium tests

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4866]
[Spec](https://docs.google.com/document/d/1aXDfb7_E7WnyOKOPXactMzheOir9T-hmgLxBRQl7xJA/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4799)

### Tasks
- [x] Selenium test plan - .5
- [x] Update test helper
- [x] Regression test for [Secure Issue 48953: App admin can elevate self to site admin](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=48953)
- [x] Regression tests for new role abilities - 3
- [x] Regression tests for hiding new role in SM - 3
- [x] Code review(s) - 1
  - https://github.com/LabKey/testAutomation/pull/1697
  - https://github.com/LabKey/sampleManagement/pull/2201
  - https://github.com/LabKey/labbook/pull/566
- [x] Teamcity review and merge - .5
