### ISSUE TITLE
In-product Upsell Messaging - automated tests

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4891]
[Spec](https://docs.google.com/document/d/17oEhOV3MEdCjzRvRKHshXGrMLESfWLT-6i_BdN5O3Ik/edit?usp=sharing)
[Scrumwise](https://www.scrumwise.com/scrum/#/backlog-item/11358-labkey-sales-marketing-community-in-product-upsell-messaging/id-1810-49095-0)
[Github epic](https://github.com/LabKey/platform/issues/4891)

### Tasks
- [x] Ramp-up - 3 📌
- [x] Automated Test Plan - 2
- [x] (add tasks) - 1
    - [x] new test class 1
    - [x] test storage of the marketing message, via mothership config page 1
    - [x] test display of the configured marketing message .5
    - [x] message can be dismissed .5
    - [x] test marketing message appears for all users and roles (incl guest) .5
- [x] Code review(s) - 1
- [ ] Code review feedback - 1
- [ ] Teamcity review and merge - 1
