### ISSUE TITLE
React 18: update react-router - Drop History Dependency, dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4919]
[Spec](https://docs.google.com/document/d/1Qi_PlPHoM2lsDjGNhK6buBk_sBoXciTxKgGfz8jXizk/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4918)

### Tasks   

- [x] Remove globals.ts (.5h)
- [x] Remove URL::getLocation (3-5h)
- [x] Update URL::setParameters methods to take a router object (3-5h)
- [x] Update UsersGridPanel to use withRouter (3-8h)
- [x] Remove History dependency from all packages and apps (0.5h) 📌
- [x] Update or create plan for provenance RunBuilder - (3-5h)
  - It uses resetParameters, but it doesn’t use react-router, so we need to make a version that uses window.location
- [x] code review(s) - 2
- [x] Teamcity review and merge - 1
