### ISSUE TITLE
React 18: update react-router - Upgrade React Router, dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#4920]
[Spec](https://docs.google.com/document/d/1Qi_PlPHoM2lsDjGNhK6buBk_sBoXciTxKgGfz8jXizk/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues/4918)

### Tasks   📌

- [x] Move AppContexts to App wrapper (1-3h) 
- [x] Update components to not use `routes` (1-3h)
- [x] add withRouterDeprecated (1h) 
- [x] Update components to use withRouterDeprecated (5-8h)
- [x] Update FC components using withRouter to use RR hooks (3-5h)
- [x] Fix issue with React Hot Loader (3-5h)
- [x] Update SubNav usages to use SubNav Context instead (3-5h)
- [x] Update useRouteLeave/withRouteLeave (3-5h)
- [x] Update Biologics Router Definition (3-5h) 
- [x] Update SampleManager Router Definition (3-5h)
- [x] Update FreezerManager Router Definition (1h)
- [x] Update unit tests (3-5h)
- [x] Fix selenium tests (3-5h) 📌
- [x] Code review(s) - 2
- [x] Checkin with @labkey-alan on Bug Bash - .25 @labkey-robert 
- [x] [Bug bash ](https://docs.google.com/document/d/1hWANK2LyA08BKNBtI86iOMZfpXAw21oMtkWNUTwyxFE/edit?usp=sharing) scheduled Monday Dec 18 at 2pm, spec created.s- 1 
- [x] Feedback from Bug Bash - 3 @labkey-alan  
- [x] Teamcity review and merge - 📌
