### ISSUE TITLE
Issue 49069: Ability to require that visits exist before entering data for them

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#5050]
[Issue 49069: ability to require that visits exist before entering data for them](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49069)
**Harvest**: LabKey R&D - Client Requested Improvements - Issue 49069: Ability to require that visits exist before entering data for them

### Overview
LabKey users are currently navigating challenges with visit data entry, as the system defaults to the creation of new visits when a sequence number is entered that doesn't already exist in the study. This has led to unintentional creation of new visits and inconsistencies in study data.

### User Stories
Data Administrator's Story: "As an administrator, I need a system that automatically checks data against predefined visits to prevent incorrect visit creation. This will ensure data accuracy and consistency in our studies."

### Proposed Solution
The enhancement involves implementing a feature in LabKey that mandates the use of predefined visits (or timepoints) before allowing data entry. This change aims to prevent the automatic creation of new visits unless they match an existing visit in the study.

### Expected Outcomes 
By introducing this feature, we anticipate:

- Greater data integrity and consistency across studies.
- A more intuitive and error-free data entry process for users.
- A reduction in support requests related to visit data issues.

### Tasks

- [x] UI to toggle configuration - 2
- [x] Round-trip setting in Db - 3
- [x] Wire up check plus error messages - 5 
- [x] Ensure all pathways are covered
  - [x] Dataset import (bulk, single row, API) - 3
  - [x] Link to study - 2
  - [x] Folder import - 2
  - [x] Specimen import - 2
  - [x] Publish study - 1
  - [x] Ancillary study - 1
  - [x] REDCap - 1 (REDCap & CDISC should work because we always export a visit map)
  - [x] CDISC-ODM - 1
- [x] Consolidate existing folder import check - 3
- [x] Update UI for existing folder import check - 3
- [x] Import/Export support - 3
- [x] Support date based studies - 2
- [x] Manual test plan (please write test plan in-line in this story card) - 1
- [x] Manual Testing  - 8 @labkey-tchad 📍
- [x] Code review - 2
- [x] Docs handoff - .5
- [x] Teamcity review and merge - .5
- [ ] Create separate story for integration tests/selenium test plan recommendations - .5

#### Manual test plan
There is a study level setting to control whether automatic creation of visit is allowed. The new setting is on the `manage visits` page and on the `manage timepoints` page for date based studies.

![Image](https://github.com/LabKey/platform/assets/5741543/73703bf8-244c-4672-9c21-c95934bfaaf7)
 
- Ensure all pathways are covered and that if the import is disallowed, an appropriate error message is presented.
  - [x] Dataset import (bulk, single row, API)
    - [Issue 49335: Dataset import with visit map throws bad error for missing visit label](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49335) (out of scope)
    - 🔴 Import for demographics dataset(s) auto-assigns visit `-1.0` if no sequence number is specified. Single row insert for demographics datasets doesn't show sequence or visit fields and will fail if visit `-1.0` isn't defined.
  - [x] Link to study
    - ✅ ~Visit creation errors don't cause auto-link pipeline job to fail.~
  - [x] Shared visits
    - ✅ ~Setting isn't respected when importing data into subfolder.~
  - [x] Folder import. If the folder archive contains a visit map the timepoint creation flag will have not effect since timepoints are created from the visit map not automatically based on data import.
  - [x] Specimen import
  - [x] Verify publish and ancillary studies can be created from a source that disallows new timepoint creation. The new studies should not allow any new data.
    - ✅ ~Specimen refresh doesn't give any indication that some specimens were skipped because the visit doesn't exist in the target study.~
  - [x] Verify REDCap imports continue to function. This should always work because a visit map is always included.
  - [x] Verify round-tripping of the new setting.

**Comment by labkey-tchad** [comment]
Manual testing:
- [x] Dataset import (bulk, single row, API)
  - [Issue 49335: Dataset import with visit map throws bad error for missing visit label](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49335) (out of scope)
  - Import for demographics dataset(s) auto-assigns visit `-1.0` if no sequence number is specified. Single row insert for demographics datasets doesn't show sequence or visit fields and will fail if visit `-1.0` isn't defined.
- Link to study -📍
- Folder import. If the folder archive contains a visit map the timepoint creation flag will have not effect since timepoints are created from the visit map not automatically based on data import.
- Specimen import
- Verify publish and ancillary studies can be created from a source that disallows new timepoint creation. The new studies should not allow any new data.
- Verify REDCap imports continue to function. This should always work because a visit map is always included.
- Verify round-tripping of the new setting.
