### ISSUE TITLE
Moving entities between projects - API dev - labkey-api-python

### ISSUE THREAD

**Issue by cnathe** [LabKey/platform#5095]
[Epic](https://github.com/LabKey/sampleManagement/issues/1652)
[Spec](https://docs.google.com/document/d/1yyD9UqQ0OZolrdQcI5El-Q2cRuG1TywmB8KJhBbAbKQ/edit#heading=h.1o86pkhr34w6)

### Tasks 📍
- [x] add move_rows to package - 2h
- [x] Code Review @labkey-alan 📍
- [x] Test review and merge📍
