### ISSUE TITLE
[LabKey CI] Tomcat 10 upgrade

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/platform#5096]
### Stories
- [x] [Tomcat 10 upgrade miscellaneous tasks](https://github.com/LabKey/platform/issues/5098)
- [x] [Tomcat 10 APR Issue -Investigation](https://github.com/LabKey/kanban/issues/12)
- [x] [Switch to Tomcat 10 standalone for EC2 and trial ](https://github.com/LabKey/cloud/issues/148)
- [x] LabKey/platform#5192
- [x] [Ensure we handle all properties currently configurable through ROOT.xml/labkey.xml](https://github.com/LabKey/platform/issues/5140)
- [x] LabKey/platform#5149
- [x] LabKey/platform#5151
- [x] LabKey/tutorialModules#176
- [x] LabKey/platform#5161
- [x] https://github.com/LabKey/kanban/issues/54
- [x] https://github.com/LabKey/server/issues/725
- [x] https://github.com/LabKey/platform/issues/5264
- [x] LabKey/platform#5152
- [x] Gradle Plugin Updates for Embedded Tomcat on TeamCity
- [x] Embedded Tomcat remote pipeline support
