### ISSUE TITLE
[LK CI] Tomcat 10 upgrade miscellaneous tasks

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/platform#5098]
[GitHub Epic](https://github.com/LabKey/platform/issues/5096)

### Tasks 📍
- [x] Update GWT @labkey-adam 
- [x] Mondrian work @labkey-matthewb  2hr 
- [ ] ~~Merge Tomcat 10 changes to develop and test~~
- [x] Test Tomcat 10 with Dockerfile @labkey-willm

**Comment by wendyinnis** [comment]
---
