### ISSUE TITLE
Plate Sets - Plate Types (server) - dev

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5114]
[Spec](https://docs.google.com/document/d/1UapOPmM0QJ3vWlBbxYFm7vHe2oycWs9f_8xSede8udc/edit#heading=h.x8pj9t8hkau)
[Github epic](https://github.com/LabKey/biologics/issues/2531)
fb_plate_type_schema (platform, commonAssays)

#### Background
Plate types represent the physical plate that an experiment might be performed upon and typically are described in the number of wells on the plate (rows and columns). We want to be able to support a plate type column on plates that could be a lookup to a plate type table. LabKey server does have the notion of plate types but they are not defined in the database and, instead are defined in java code and registered by a `PlateTypeHandler`. The motivation for this abstraction is to allow plate type handlers to create plates (or templates) which have predefined well groups (controls, replicates, samples, etc.) to simplify the workflow during plate template creation for our supported assay types (NAb, ELISpot, ELISA, Standard). This is less important in the application workflow and will become obsolete when we have a modern plate designer/editor.

For this story, the goal is to decouple plate type registration from the handlers and move to a model where types are defined and sourced from the database but still maintain handlers for the legacy workflow where well group creation is important.

### Tasks 
- [x] Plate type schema - 2hr
- [x] Update plate schema - 1hr
- [x] Query support - 2hr
- [x] Refactor
  - [x] Separate PlateType from PlateTypeHandler - 3hr
  - [x] Create `PlateLayout` and `PlateLayoutHandler` - 2hr
  - [x] Replace rows/columns with `PlateType` param - 3hr
  - [x] Update `PlateService` with new signatures - 2hr
- [x] Clean up endpoints - 2hr
- [x] Plate upgrade script
  - [x] Replace type with plate type ID - 1hr
  - [x] Remove rows & columns fields? - 1hr
- [x] Junit tests - .5hr
- [x] Rename "type" to "assayType". - 1hr 
- [x] Repurpose "PlateType" as what is currently "PlateTypeId" - 1hr
- [x] Introduce "archived" column to plate.PlateType and set 1536 and invalid plate types to archived = true - .5hr
- [x] Add a "PlateID" column to plate.Plate and replicate name expression value into "PlateID" column - 1hr
- [x] Add a "PlateSetID" column to plate.PlateSet and replicate name expression value into "PlateSetID" column - 1hr
- [x] Add a "WellsFilled" column to plate.Plate - 1hr
- [x] Code review - 1hr
- [x] Teamcity review and merge - 1hr
