### ISSUE TITLE
[LK CI] Ensure we handle all properties currently configurable through ROOT.xml/labkey.xml

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/platform#5140]
[Tomcat 10 upgrade Github epic](https://github.com/LabKey/platform/issues/5140)

### Tasks 📍

- [x] Propagate JMS, LDAP, and other settings from application.properties
- [x] Update comments and error messages
- [x] Redirector for legacy context paths
- [x] Handle HTTP and HTTPS concurrently
- [x] Handle session timeout correctly
- [x] Debug config for free IntelliJ
- [x] Fix Mondrian unit tests
- [x] Fix JSP recompilation
- [x] Revisit application.properties handling for JMS, etc
- [x] Fix additional web apps📍
- [x] doc handoff
