### ISSUE TITLE
Plate Architecture : Convert well properties to provisioned table

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#5166]
[Spec](https://docs.google.com/document/d/1i6qP3inaj5fFD6z0M-ZpaD4HLPmj1Z4wuj3BvmKRqFg/edit)

 In a previous story, custom plate properties were implemented using a `vocabulary domain` which was joined to the `assay.well` table. The domain was scoped at the project level. Vocabulary domain are simple to add support for a table because of previous work that Kevin did in both the `UserSchema` and `QueryUpdateService`. However, vocabulary domains rely on `Ontology` to store and resolve values and is not as efficient as a provisioned solution. The conclusion was made that vocab domains are not a good match for plates and the decision was made to move towards a solution that joins the well data to a domain backed by a provisioned table.

Additionally, since the existing behavior was never exposed outside of an experimental flag, we plan to not support migrating from one domain to another and instead will drop the vocabulary domains on upgrade.

#### Tasks
- [x] WellDomainKind - 2 hr
- [x] Refactor PlateService endpoints to use new domain - 2 hr
- [x] Remove support in WellTable for vocabulary domains - 1 hr
- [x] Join WellTable to provisioned table - 1 hr
- [x] Remove support in WellUpdateService for vocab domains - 1 hr
- [x] Update WellUpdateService to insert in to both well and properties table - 3 hr
- [x] Clean up provisioned rows on plate or container delete - 3 hr
- [x] Drop well vocabulary domains - 2 hr
- [x] Drop assay.plateProperty values - 1 hr
- [x] Update junit tests, api endpoints - 2 hr
- [x] code reviews - 1
- [x] Manual Testing - 2 @labkey-chrisj 
- [ ] tc review and merge -1

**Comment by labkey-andrewo** [comment]
Will this have any impact on how the user experiences defining plate metadata?

**Comment by labkey-nicka** [comment]
> Will this have any impact on how the user experiences defining plate metadata?

There is no intention of changing the UX.
