### ISSUE TITLE
[LabKey CI] Switch to Tomcat10 standalone for EC2 and trial follow up

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/platform#5192]
[Tomcat 10 upgrade epic](https://github.com/LabKey/platform/issues/5096)
###Tasks
- [x] Update Lave scaffold.sh to include new ami build targets @labkey-stuartm 
- [x] Testing @labkey-stuartm 
- [x] Code review
- [x] Merge @labkey-stuartm 
- [x] Update Teamcity build/scripts for cleanup @labkey-stuartm 
- [x] Secure Issue [#49587 ](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=49587)- Mail Helper startup error @labkey-stuartm 
- [x] Code review (for issue 49587) @labkey-willm 
- [x] TC verify and merge
