### ISSUE TITLE
[LabKey Cloud] CSP: LKSM strict enforce rollout

### ISSUE THREAD

**Issue by labkey-adam** [LabKey/platform#5212]
[Content security policy roll out epic](https://github.com/LabKey/cloud/issues/153)
[CSP Warnings](https://docs.google.com/spreadsheets/d/1Rdy5nM6YSgXUg2NmBnsr3_xS0lv5WApaNlvsQu3mUAs/edit#gid=0)
### Tasks  📍
- [x] Correct Google Analytics settings for all EC2-to-container migrated deployments - @labkey-stuartm 
- [x] Deploy strict enforce CSP to fire @labkey-willm 
- [x] Deploy strict enforce CSP to aqua @labkey-willm 
- [x] review logs for fire and aqua @labkey-adam @mbellew @labkey-susanh 
- [x] Verify google translate and bartender on Chrome, Safari and Firefox @labkey-susanh @labkey-ians 
- [x] Daily updates

**Comment by wendyinnis** [comment]
[Susan]
My initial testing of using Google Translate with the CSP indicates that it doesn't work at all (either locally or on fire) on Chrome.
Locally, if I modify my CSP to use:
connect-src 'self' ws: ${LABKEY.ALLOWED.CONNECTIONS} translate-pa.googleapis.com translate.googleapis.com ;
and 
img-src 'self' https: data: http://chart.apis.google.com translate.google.com ;
I get no errors and the page does get translated.
