### ISSUE TITLE
Path to React 18 - Product menus

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5213]
[Spec](https://docs.google.com/document/d/1mBcmpqdl6mBFi-WK35JFqsdggsvSb-h54DtYiebTyl0/edit?usp=sharing)
[Github epic ](https://github.com/orgs/LabKey/projects/3/views/3?pane=issue&itemId=42825482)

### Tasks 📍 
- [x] ProductMenu (2-3h)
- [x] ServerNotifications (2-3h)
- [x] ProductNavigation (2-3h)
- [x] Fix styling (2-3h)
- [x] FilterExpressionView (1h)
- [x] Fix selenium tests (2-3h)
- [x] Fix unit tests (1-2h) 
- [x] Code review(s) - 2
- [x] Teamcity review and merge - 1 📍
