### ISSUE TITLE
[NeuroTRC CognitionMS] Setup the Compliant Cloud Product Environment

### ISSUE THREAD

**Issue by labkey-adam** [LabKey/platform#5242]
### Tasks

- [x] Spin up NeuroTRC demo server to allow export of content - @labkey-jony 
- [x] Retrieve content from demo server - @labkey-klum 
- [x] Spin down NeuroTRC demo server - @labkey-jony 
- [x] Spin up production CognitionMS environment - @labkey-jony 
- [x] Configure CognitionMS production server - @labkey-klum
