### ISSUE TITLE
SampleType MaterializedViews: Remove Experimental Flag

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5287]
### Tasks
- [x] dev - .1 @labkey-matthewb 
- [x] code review - .5 @labkey-susanh 📍 
- [x] TC review and merge - 1 @labkey-matthewb 📌
