### ISSUE TITLE
[LabKey R&D - EHR] Migrate EHR inline event handlers

### ISSUE THREAD

**Issue by labkey-adam** [LabKey/platform#5330]
[Known Inline Handlers](https://docs.google.com/spreadsheets/d/1Rdy5nM6YSgXUg2NmBnsr3_xS0lv5WApaNlvsQu3mUAs/edit#gid=1144908588)

### Tasks
- [x] Eliminate inline handlers from SnapshotPanel.js. ehrModules & nircEHRModules @ankurjuneja 
- [x] Eliminate inline handlers from SnapshotPanel.js and snprcOverrides.js. onprcEHRModules and snprcEHRModules @ankurjuneja 
- [x] Migrate inline handlers out of EHRCustomizers and various display columns in ehrModules. See spreadsheet for full list @ankurjuneja 
- [x] Migrate inline handlers out of EHRCustomizers and various display columns in onprcModules. See spreadsheet for full list @ankurjuneja 
- [x] Decide what to do about WebUtils/lk-table.jsp: migrate? ignore? eliminate? @ankurjuneja 
- [x] JHU ClinPathRuns.js @ankurjuneja 
- [x] MenuBarHoverNavigation.js used by EHR, JHU, SNPRC quickSearch. Should we reconcile with ONPRC quickSearch approach? Use UIComponents navigation.js instead? @ankurjuneja 
- [x] LabDevKitModules/Printer.js has a couple inline onclick handlers. These could be migrated, but I see no usages of this JS file. Please confirm and delete. @ankurjuneja 
- [x] Code review
- [x] TC Review and merge
