### ISSUE TITLE
[LKCRI] Issue 49822: Pipeline does not show a job as failed for if DB fails over to secondary server

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5336]
[Issue 49822: Pipeline does not show a job as failed for if DB fails over to secondary server](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49822)

Target Release: 24.3 maintenance release

### Tasks 📍 
- [x] Dev - 5
- [x] Manual Testing - 2 @labkey-danield 
- [x] Code reviews - 1 @labkey-susanh 
- [x] Manual Testing feedback - .5 @labkey-jeckels 
- [x] TC Review and Merge - 1
