### ISSUE TITLE
Path to React 18 - Reduce react-bootstrap usages (part 1, timeboxed)

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5500]
[Spec](https://docs.google.com/document/d/1mBcmpqdl6mBFi-WK35JFqsdggsvSb-h54DtYiebTyl0/edit?usp=sharing)
[Github epic ](https://github.com/orgs/LabKey/projects/3/views/3?pane=issue&itemId=42825482)

### Tasks
- [x] Remove usages of react-bootstrap (timeboxed)
- [x] Fix broken unit tests
- [x] Fix broken selenium tests 📌 
- [x] Code review(s) - 2
- [x] Teamcity review and merge -1
