### ISSUE TITLE
Path to React 18 - Update formsy-react

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5501]
[Spec](https://docs.google.com/document/d/1mBcmpqdl6mBFi-WK35JFqsdggsvSb-h54DtYiebTyl0/edit?usp=sharing)
[Github epic ](https://github.com/orgs/LabKey/projects/3/views/3?pane=issue&itemId=42825482)

### Tasks
- [x] Update `formsy-react` - 10-20 📍
- [x] Code review(s) - 1 @labkey-alan @cnathe 
- [x] Manual Testing - 3 @labkey-chrisj 
- [x] TeamCity review and merge -1

**Comment by labkey-chrisj** [comment]
- Registry Wizards
- [x]   - Molecule
     - stoichiometry accepts '0' as input but submit supplies error 
- [x]   - Prot Sequence
- [x]   - Nucleotide Sequence

- Registry Forms
 - [x]  Expression System, et. al. (the rest of the built-in forms)
 
- Media Wizards
- [x] Ingredients
- [x] Raw Materials
- [x] Batch
- [x] Mixture

 - Editing Details 
- [x]   Data Classes 
     - molecular species- cysteines and disulfides can be negative (probably shouldn't)
     - molecules -  avg mass, iso, extinction, disulfides, cysteines can all be negative
     - proteins - avg mass iso, extinction, disulfides, cysteines can be negative
    
- [x]   Sample Types
- [x]   Assay Runs
- [x]  Media types
    - [x] ingredient - molecular weight field accepts 0 and negative values, probably shouldn't
    - [x] batch - edit actual amount accepts negatives
    - [x] mixture - edit details expiration time accepts negatives, 0

- [x] Freezer Storage Creation Pane
- [x] Update Plate Modal (Name and Description)
