### ISSUE TITLE
Issue 47713: Assay fields should not allow setting of PHI level since it will not be respected

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5597]
[Issue 47713: Assay fields should not allow setting of PHI level since it will not be respected](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=47713)

### Tasks

- [ ] Dev - 3 @labkey-matthewb 
- [ ] Manual Testing - 2
- [ ] Manual Testing feedback -1 
- [ ] Code review (s) -1 
- [ ] Teamcity review and merge - 1
