### ISSUE TITLE
PHI: Ensure good handling of PHI fields Cross-Container - planning

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5600]
[Spec](https://docs.google.com/document/d/1CkokKqzjkc1Ge1MlyRE6aFm2mEZpwf42F4bKrCtC8zE/edit?usp=sharing)
[Issue 47713](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=47713)
[Github epic](https://github.com/LabKey/platform/issues/5599)

### Tasks 📍
- [x] Review issue @labkey-matthewb 
- Feature Summary - 1  
  - [x] User Value Statement
  - [x] Success Metrics @labkey-hannah 
  - [x] Background
  - [x] User Stories  
- [x] Open Questions - 1 @labkey-hannah @labkey-robert @labkey-matthewb @labkey-adam 
- [x] Review updates - .5
- [x] Sync on immediate changes needed - .5 @labkey-matthewb @labkey-hannah 
- [x] Create separate Issues story
- [x] PHI Revamp [Discussion ](https://docs.google.com/document/d/1CkokKqzjkc1Ge1MlyRE6aFm2mEZpwf42F4bKrCtC8zE/edit#heading=h.bsxjosdazqh7)- 1 @labkey-hannah @labkey-adam 
- [x] Review feedback in the doc and decide on next steps @labkey-hannah
