### ISSUE TITLE
LabKey EI - Remove JSON Plate Metadata Support

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#5621]
**Tasks**
- [x] Domain run & result properties
- [x] Plate support only for LKB folders
- [x] `PlateDataDomain` and `PlateDataTable`
- [x] `AssayPlateMetadataTemplateAction , PlateMetadataDisplayColumn`
- [x] `AssayPlateMetadataService` methods
- [x] `AssayPlateMetadataService.MetadataLayer`
- [x] `PlateMetadataDataHandler`
- [x] `AssayImportRunTask.getPlateMetadata`
- [x] `AssayRunUploadContext.getRawPlateMetadata`
- [x] JSON file data collector
- [x] File watcher support
- [x] `AssayPlateMetadataService`
- [x] `ImportRunApi`
- [x] `AssayPlateDataDomainKind`
- [x] Remove Rlabkey support (createRun)
- [x] Adjust automated tests (delete GpatPlateTemplateTest & plate-metadata-1.json)
- [ ] Code reviews @cnathe @labkey-nicka @labkey-tchad
