### ISSUE TITLE
PHI: Ensure good handling of PHI fields Cross-Container - Issues

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5635]
[Spec](https://docs.google.com/document/d/1CkokKqzjkc1Ge1MlyRE6aFm2mEZpwf42F4bKrCtC8zE/edit?usp=sharing)
[Github epic](https://github.com/LabKey/platform/issues)

### Tasks
- [x] [Issue 50731: Compliance options should not change across containers (24.7, pri 2)]( https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50731) 
  - [x] Dev
  - [x] Manual Testing
  - [x] Integration Tests
  - [x] Teamcity review and merge 
- [x] [Issue 50732: Fix "Log only query access including PHI columns" for all types that support PHI (24.7, pri 3)]( https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50732)
  - [x] Dev
  - [x] Manual Testing
  - [x] Integration Tests
  - [x] Teamcity review and merge 
- [x] [Issue 50738: Linking samples with PHI to a study without PHI handling shows PHI ( 24.7, pri 2)]( https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50738)
  - [x] Dev
  - [x] Manual Testing
- [x] Communicate to everyone who wants to know. @labkey-hannah 

~~[Issue 50752: Consider changing default "maxAllowedPhi" when compliance module is installed (https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50752)~~

see also https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50754
