### ISSUE TITLE
Path to React 18 - Reduce react-bootstrap usages (part 2)

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/platform#5646]
[Spec](https://docs.google.com/document/d/1mBcmpqdl6mBFi-WK35JFqsdggsvSb-h54DtYiebTyl0/edit?usp=sharing)
[Github epic ](https://github.com/orgs/LabKey/projects/3/views/3?pane=issue&itemId=42825482)

### Tasks
- [x] Remove usages in ui-components
- [x] Remove usages in ui-premium (eln)
- [x] Remove usages in limsModules
- [x] Remove usages in provenance
- [x] Remove usages in other modules
- [x] Fix selenium tests
- [x] Fix unit tests 
- [x] Code review(s)
    - [x] ui-components
    - [x] ui-premium
    - [x] platform
    - [x] limsModules
    - [x] testAutomation
    - [x] moduleEditor
    - [x] provenance
- [x] TC review and merge
    - [x] ui-components
    - [x] ui-premium
    - [x] platform
    - [x] limsModules
    - [x] testAutomation
    - [x] moduleEditor
    - [x] provenance
