### ISSUE TITLE
AbDisc: Perf regression investigation

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#5696]
**Tasks**
- [x] Review failures : 2
- [x] Analyze code changes : 2
- [x] Profile plate set creation : 2
- [x] Defer container delete in `PlateSetPerfTest` : 1
- [x] Review new baseline : 3
- [x] Review table indices : 3
- [x] Defer plate indexing in bulk operations : 3
