### ISSUE TITLE
[LabKey CRI] Link to study support for visit labels

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#5699]
[spec](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=50224)

When importing data into visit based studies that have a visit map configured, specifying a visit label in the imported data will correctly map to the associated sequence number. However, this is not supported in the link to study scenarios and we always expect a sequence number for sample data.

This work adds the capability to use visit labels in place of sequence numbers when linking sample data to visit based studies.

**Tasks**
-  [x] New data type for sample result domains.
- [x] Client side changes
- [x] Publish confirm action
- [x] Sample type field key resolution
- [x] Derived sample support
- [x] Auto-link support
- [x] Feature verification @labkey-hannah @jryurkanin 
- [x] Manual test @labkey-sweta 
- [x] Automation test

> - [x] Create new CreateNewVisitPage
> - [x] testVisitLabelLinkToStudy() test case
> - [x] testVisitLabelAutoLinkToStudy() test case

- [x]  Code review for automation
- [x] Code review & merge
