### ISSUE TITLE
[LabKey CRI] LabKey CRI - Issue 48158: Delete study participant feature - planning

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/platform#5936]
[Issue 48158](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=48158)
[Spec](https://docs.google.com/document/d/1c1GLcFopNTvw1ySMRr0omW4i0PGQAxBl7VhEsKpw3MA/edit?usp=sharing)
[Github epic](https://github.com/orgs/LabKey/projects/5/views/2?pane=issue&itemId=83655160&issue=LabKey%7Cplatform%7C5951)

### Tasks 📍
- [x] Functional Spec @labkey-bpatel  
- [x] Sync with Hannah
- [x] Functional Spec Review
- [x] Implementation Details @labkey-bpatel
- [x] Dev Review @labkey-adam @labkey-jeckels 
- [x] Test Review @labkey-danield  
- [x] Sync with Hannah
- [x] Update Spec with feedback
