### ISSUE TITLE
LabKey CRI - Issue 48158: Delete study participant feature - dev

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/platform#6011]
[Issue 48158: Delete study participant feature](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=48158)
[Spec](https://docs.google.com/document/d/1c1GLcFopNTvw1ySMRr0omW4i0PGQAxBl7VhEsKpw3MA/edit?tab=t.0) 
### Tasks 📍 
- [x] Update text and link - 0.5 hr
- [x] Add 'Delete Participant' section - 1 hr
- [x] Implement 'Delete' Action - 5 hrs
- [x] Test Delete
- [x] UI Feedback and Error Handling - 3 hrs
- [x] Add 'View Participant Data' link - 0.5 hrs
- [x] Dynamically load combo box data - 2 hrs
- [x] Add audit log for deleting from ParticipantGroupMap table 
- [x] Code Review - 1 hr @josheckels @labkey-klum 
- [x] Code Review changes @labkey-bpatel
- [x] Update Spec - 1 hr 
- [x] Create test plan - 1hr
- [x]  Review code updates @josheckels @labkey-klum 
- [x] TC Verify and merge - 0.5
- [x] Doc handoff
