### ISSUE TITLE
Remove deprecated GWT study designs

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/platform#6099]
[tracking issue](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=51724)

### Tasks
- [x] Update CAVD folder type
- [x] Remove classes related to the GWT classes
- [x] Remove deprecated feature flag
- [x] Update / fix automated tests
- [x] Manual test (upgrade & new folder scenarios) @cnathe 
- [x] Code review @cnathe
